import ReactDOMServer from 'react-dom/server'
import Head from 'next/head'
import Image from 'next/image'
import { usePersistedContext } from 'react-persist-context'
import styles from '../styles/Home.module.css'

export default function Home() {
  const { state, dispatch } = usePersistedContext()
  const increaseCount = () => {
    dispatch({
      type: 'INCREASE_COUNT'
    })
  }
  const decreaseCount = () => {
    dispatch({
      type: 'DECREASE_COUNT'
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <h1>count: { state && state.count} </h1>
     <button type="button" onClick={increaseCount}>
       increase Count
     </button>
     <button type="button" onClick={decreaseCount}>
       decrease count
     </button>
    </div>
  )
}